# define context fields?

levels:
    type: manual
    steps: [100,250,400,750,1100]

XPs:
    # XP is predefined
    - postXP

events:
    ForumPost:
        actions:
            - xp:
                name: postXP
                amount: 1
            - xp:
                name: XP
                amount: 10
    QuestionAsked:
        actions:
            - xp:
                name: XP
                amount: 2
    VoluntarySelfTestTaken: ~
    CourseCompleted:
        actions:
            - xp:
                name: XP
                amount: 20
    VideoClicked: ~
    SelfAssigmentStarted: ~
    SelfTestStarted: ~
    X: ~


achievements:
    AnyOfEventAchievement:
        requirements:
            - event:
                name: X
                conditions:
                  - AnyOf:
                      - parameter: Kim
                        value: gross
                      - AnyOf:
                          - parameter: Frede
                            value: schoen
                          - parameter: Kim
                            value: hobbit

    CommunicatorBronze:
        #meta de mai jos e definit ca un Map/(HashTable)/Key:value. Daca punem "-" in fata key, rezultatul va fi un vector de obiecte [ { culoare: '#890123' }, ...] ceea ce nu vrem...
        meta:
            color: "#890123"
            image: "https://econ.unitbv.ro/images/UNIVTB-01.png"
            details: "bla bla 1"
            title: "un nou inceput!"
            desc: "d sakldl ksf nsdkjfs nfkjsd nfk js nfksj f nskjfsd kjfs"
        requirements:
            - xp:
                name: postXP
                amount: 2
        actions:
            - xp:
                name: XP
                amount: 23
        hidden: true

    CommunicatorSilver:
        meta:
            culoare: "#AA00AA"
            imagine: "https://econ.unitbv.ro/images/UNIVTB-01.png"
            detaliu: "bla bla 2"
            title: "sa continuam!"
            desc: "alta descriere jmekera"
        requirements:
            - achievement:
                name: CommunicatorBronze
            - xp:
                name: postXP
                amount: ">= 5"
        replaces: [CommunicatorBronze]

    ComCom:
        requirements:
            - event:
                name: ForumPost
                amount: ">= 10"

    VoluntarySelfTestTakenAward:
        requirements:
            - event:
                name: VoluntarySelfTestTaken
                conditions:
                    - parameter: completion_percentage
                      value: 100
        # maxAwarded and maxAwardedTotal are implicitly 1
        # maxAwarded: 1
        # maxAwardedTotal: 1

        # could be e.g. per user and course, could be renamed to "per"
        scope: [user]
        actions:
            - xp:
                name: XP
                amount: 2

    JavaPro:
        requirements:
            - event:
                name: CourseCompleted
                amount: 5
                conditions:
                    - parameter: tags
                      value: java
        scope: [user]

    # achievement per completed course
    CourseCompletedAward:
        requirements:
            - event:
                name: CourseCompleted
        scope: [user, context.course_id]

    ContinousAttendance:
        requirements:
        # VideoClicked AND (SelfTestStarted OR SelfAssigmentStarted)
            - event:
                name: VideoClicked
                conditions:
                    - parameter: watched_videos_of_week_percentage
                      value: ">= 70"
            - AnyOf:
                - event:
                    name: SelfTestStarted
                - event:
                    name: SelfAssigmentStarted
        hidden: true
        scope: [user, context.course_id, context.course_week]
        actions:
            - xp:
                name: XP
                amount: 10
                requirements:
                  - achievement:
                      name: ContinousAttendance
                      conditions:
                          - parameter: context.user_id
                            value: user_id
                          - parameter: context.course_week
                            value: course_week -1
                          - parameter: context.course_id
                            value: course_id
